repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.291'
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: pytest
        name: pytest-check
        entry: poetry run pytest
        language: system
        pass_filenames: false
        # Runs only on python files
        types: [ python ]
        always_run: true
